### ISSUE TITLE
animated height map / isolines

### ISSUE THREAD

**Issue by hatsumatsu** [leon196/CookieInvitro2017#1]
Hey, I stumbled upon your demo on [http://leon196.github.io/season/index.html](http://leon196.github.io/season/index.html) , crazy cool! 🔥

Some time ago I was researching into animating height maps with isolines like the ones you use in the sky of your demo but didn't find a good solution. Can you share some details of how you built these? Couldn't find it in the repo...

Thanks a lot!

Martin

**Comment by leon196** [comment]
Hi Martin,

Thanks. For rendering lines, I'm using a post processing effect. It's an edge filter.
I'm using it here:
https://github.com/leon196/CookieEngine/blob/a397c322c630f039137b29a6a25f5f3d045921c5/browser/asset/shader/postprocess.frag#L20
And it's defined here:
https://github.com/leon196/CookieEngine/blob/a397c322c630f039137b29a6a25f5f3d045921c5/browser/asset/shader/header.glsl#L140

I'm using threshold on colors, so I can choose the number of shades a color can get, thus the number of lines. The interpolation between colors is made either with dot product with normal or a simple perlin noise. So if you looking for animating theses lines, you could animate the perlin noise.

**Comment by hatsumatsu** [comment]
Thanks a lot, the edge filter was the part I was missing!
